##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/SLNC-DIMP/juneteenth

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Juneteenth Resources
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: From NCpedia and NC Digital Collections
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: Resources about Juneteenth as well as culture, arts, history, and perseverance of African Americans in North Carolina.
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: north carolina; african americans;history
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Andrea Smythe, State Library of North Carolina

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: juneteenth-metadata 
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: State Library of North Carolina
organization-link: https://statelibrary.ncdcr.gov/
organization-logo-banner: https://static.quartexcollections.com/ncdcr/media-file/89e5af66-ebbd-428d-9dcb-dd8353724866-mastheadsingle.jpg
organization-logo-nav: /assets/img/logo_ncdc_white.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
